// Curated supply item master (data-as-code).
//
// Seeded per-school into `supply_item` on first use (see supply-service.ts).
// This is the SINGLE SOURCE OF TRUTH for the starter catalog. To push catalog
// additions to schools that are already seeded, ADD items below and BUMP
// SUPPLY_ITEM_MASTER_VERSION — the seeder inserts only the items a school does
// not already have (insert-only delta, keyed on name + category, any status).
// It never updates, deletes, or resurrects a school's existing rows.
//
// `categoryCode` must match a code in DEFAULT_SUPPLY_CATEGORIES.
// `unit` must be a value in SUPPLY_UNITS. `itemType` is 'consumable' | 'equipment'.

import { ItemType, SupplyUnit } from './supply-constants';

export const SUPPLY_ITEM_MASTER_VERSION = 1;

export interface SupplyItemSeed {
  name: string;
  categoryCode: string;
  unit: SupplyUnit;
  itemType: ItemType;
}

// Compact tuple form keeps the (large) list readable; expanded below.
type Row = [string, string, SupplyUnit, ItemType];

const ROWS: Row[] = [
  // ---------------------------------------------------------------- stationery
  ['Ball Pen Blue', 'stationery', 'piece', 'consumable'],
  ['Ball Pen Black', 'stationery', 'piece', 'consumable'],
  ['Ball Pen Red', 'stationery', 'piece', 'consumable'],
  ['Gel Pen Blue', 'stationery', 'piece', 'consumable'],
  ['Gel Pen Black', 'stationery', 'piece', 'consumable'],
  ['Gel Pen Red', 'stationery', 'piece', 'consumable'],
  ['Fountain Pen', 'stationery', 'piece', 'consumable'],
  ['Ink Bottle Blue', 'stationery', 'bottle', 'consumable'],
  ['Ink Bottle Black', 'stationery', 'bottle', 'consumable'],
  ['Ink Cartridge', 'stationery', 'packet', 'consumable'],
  ['Pencil HB', 'stationery', 'piece', 'consumable'],
  ['Pencil 2B', 'stationery', 'piece', 'consumable'],
  ['Mechanical Pencil', 'stationery', 'piece', 'consumable'],
  ['Pencil Lead Refill 0.5mm', 'stationery', 'packet', 'consumable'],
  ['Pencil Lead Refill 0.7mm', 'stationery', 'packet', 'consumable'],
  ['Eraser', 'stationery', 'piece', 'consumable'],
  ['Dust-Free Eraser', 'stationery', 'piece', 'consumable'],
  ['Pencil Sharpener', 'stationery', 'piece', 'equipment'],
  ['Dual-Hole Sharpener', 'stationery', 'piece', 'equipment'],
  ['Sharpener with Box', 'stationery', 'piece', 'equipment'],
  ['Wooden Ruler 15cm', 'stationery', 'piece', 'consumable'],
  ['Wooden Ruler 30cm', 'stationery', 'piece', 'consumable'],
  ['Plastic Scale 30cm', 'stationery', 'piece', 'consumable'],
  ['Steel Ruler 30cm', 'stationery', 'piece', 'equipment'],
  ['Set Square Pair', 'stationery', 'pair', 'consumable'],
  ['Protractor', 'stationery', 'piece', 'consumable'],
  ['Geometry Box', 'stationery', 'set', 'equipment'],
  ['Divider', 'stationery', 'piece', 'consumable'],
  ['Compass', 'stationery', 'piece', 'consumable'],
  ['Highlighter Yellow', 'stationery', 'piece', 'consumable'],
  ['Highlighter Green', 'stationery', 'piece', 'consumable'],
  ['Highlighter Pink', 'stationery', 'piece', 'consumable'],
  ['Highlighter Set', 'stationery', 'set', 'consumable'],
  ['Permanent Marker Black', 'stationery', 'piece', 'consumable'],
  ['Permanent Marker Blue', 'stationery', 'piece', 'consumable'],
  ['Whiteboard Marker Black', 'stationery', 'piece', 'consumable'],
  ['Whiteboard Marker Blue', 'stationery', 'piece', 'consumable'],
  ['Whiteboard Marker Red', 'stationery', 'piece', 'consumable'],
  ['Whiteboard Marker Green', 'stationery', 'piece', 'consumable'],
  ['Whiteboard Marker Set', 'stationery', 'set', 'consumable'],
  ['Marker Refill Ink', 'stationery', 'bottle', 'consumable'],
  ['Whiteboard Duster', 'stationery', 'piece', 'consumable'],
  ['Chalk White', 'stationery', 'box', 'consumable'],
  ['Chalk Coloured', 'stationery', 'box', 'consumable'],
  ['Dustless Chalk', 'stationery', 'box', 'consumable'],
  ['Duster Cloth', 'stationery', 'piece', 'consumable'],
  ['Correction Pen', 'stationery', 'piece', 'consumable'],
  ['Correction Tape', 'stationery', 'piece', 'consumable'],
  ['Correction Fluid', 'stationery', 'bottle', 'consumable'],
  ['Glue Stick', 'stationery', 'piece', 'consumable'],
  ['Liquid Glue', 'stationery', 'bottle', 'consumable'],
  ['Gum Bottle', 'stationery', 'bottle', 'consumable'],
  ['Cello Tape', 'stationery', 'roll', 'consumable'],
  ['Masking Tape', 'stationery', 'roll', 'consumable'],
  ['Double-Sided Tape', 'stationery', 'roll', 'consumable'],
  ['Brown Packing Tape', 'stationery', 'roll', 'consumable'],
  ['Tape Dispenser', 'stationery', 'piece', 'equipment'],
  ['Stapler Small', 'stationery', 'piece', 'equipment'],
  ['Stapler Medium', 'stationery', 'piece', 'equipment'],
  ['Stapler Heavy Duty', 'stationery', 'piece', 'equipment'],
  ['Staple Pins No.10', 'stationery', 'box', 'consumable'],
  ['Staple Pins 24/6', 'stationery', 'box', 'consumable'],
  ['Staple Remover', 'stationery', 'piece', 'equipment'],
  ['Paper Clips', 'stationery', 'box', 'consumable'],
  ['Binder Clips Small', 'stationery', 'box', 'consumable'],
  ['Binder Clips Large', 'stationery', 'box', 'consumable'],
  ['U Pins', 'stationery', 'box', 'consumable'],
  ['Drawing Pins', 'stationery', 'box', 'consumable'],
  ['Push Pins', 'stationery', 'box', 'consumable'],
  ['Rubber Bands', 'stationery', 'packet', 'consumable'],
  ['Sticky Notes', 'stationery', 'pad', 'consumable'],
  ['Flag Sticky Notes', 'stationery', 'packet', 'consumable'],
  ['Sketch Pen Set', 'stationery', 'set', 'consumable'],
  ['Marker Stand', 'stationery', 'piece', 'equipment'],
  ['Pen Stand', 'stationery', 'piece', 'equipment'],
  ['Scissors Small', 'stationery', 'piece', 'equipment'],
  ['Scissors Large', 'stationery', 'piece', 'equipment'],
  ['Paper Cutter Knife', 'stationery', 'piece', 'equipment'],
  ['Cutter Blade Refill', 'stationery', 'packet', 'consumable'],
  ['Calculator Basic', 'stationery', 'piece', 'equipment'],
  ['Calculator Scientific', 'stationery', 'piece', 'equipment'],

  // -------------------------------------------------------------------- paper
  ['A4 Paper 70 GSM', 'paper', 'ream', 'consumable'],
  ['A4 Paper 80 GSM', 'paper', 'ream', 'consumable'],
  ['A3 Paper', 'paper', 'ream', 'consumable'],
  ['Legal Size Paper', 'paper', 'ream', 'consumable'],
  ['Chart Paper White', 'paper', 'sheet', 'consumable'],
  ['Chart Paper Coloured', 'paper', 'sheet', 'consumable'],
  ['Craft Paper', 'paper', 'sheet', 'consumable'],
  ['Glaze Paper', 'paper', 'sheet', 'consumable'],
  ['Crepe Paper', 'paper', 'roll', 'consumable'],
  ['Handmade Paper', 'paper', 'sheet', 'consumable'],
  ['Origami Paper', 'paper', 'packet', 'consumable'],
  ['Card Stock', 'paper', 'sheet', 'consumable'],
  ['Ivory Sheet', 'paper', 'sheet', 'consumable'],
  ['Mount Board', 'paper', 'sheet', 'consumable'],
  ['Foam Board', 'paper', 'sheet', 'consumable'],
  ['Tracing Paper', 'paper', 'sheet', 'consumable'],
  ['Graph Paper', 'paper', 'packet', 'consumable'],
  ['Ruled Notebook', 'paper', 'piece', 'consumable'],
  ['Unruled Notebook', 'paper', 'piece', 'consumable'],
  ['Long Notebook', 'paper', 'piece', 'consumable'],
  ['Practical Notebook', 'paper', 'piece', 'consumable'],
  ['Drawing Book', 'paper', 'piece', 'consumable'],
  ['Register 200 Pages', 'paper', 'piece', 'consumable'],
  ['Register 400 Pages', 'paper', 'piece', 'consumable'],
  ['Attendance Register', 'paper', 'piece', 'consumable'],
  ['Log Book', 'paper', 'piece', 'consumable'],
  ['Sticky Label Sheet', 'paper', 'sheet', 'consumable'],
  ['Photo Paper', 'paper', 'packet', 'consumable'],
  ['Carbon Paper', 'paper', 'packet', 'consumable'],
  ['Butter Paper', 'paper', 'roll', 'consumable'],

  // ---------------------------------------------------------------- art_craft
  ['Wax Crayons', 'art_craft', 'box', 'consumable'],
  ['Oil Pastels', 'art_craft', 'box', 'consumable'],
  ['Colour Pencils', 'art_craft', 'box', 'consumable'],
  ['Water Colour Cakes', 'art_craft', 'box', 'consumable'],
  ['Water Colour Tubes', 'art_craft', 'set', 'consumable'],
  ['Poster Colour', 'art_craft', 'set', 'consumable'],
  ['Acrylic Colour', 'art_craft', 'set', 'consumable'],
  ['Fabric Colour', 'art_craft', 'set', 'consumable'],
  ['Glass Colour', 'art_craft', 'set', 'consumable'],
  ['Finger Paint', 'art_craft', 'set', 'consumable'],
  ['Paint Brush Set', 'art_craft', 'set', 'consumable'],
  ['Flat Paint Brush', 'art_craft', 'piece', 'consumable'],
  ['Round Paint Brush', 'art_craft', 'piece', 'consumable'],
  ['Sponge Brush', 'art_craft', 'piece', 'consumable'],
  ['Palette', 'art_craft', 'piece', 'equipment'],
  ['Drawing Easel', 'art_craft', 'piece', 'equipment'],
  ['Canvas Board', 'art_craft', 'piece', 'consumable'],
  ['Modelling Clay', 'art_craft', 'packet', 'consumable'],
  ['Play Dough', 'art_craft', 'packet', 'consumable'],
  ['Plaster of Paris', 'art_craft', 'kg', 'consumable'],
  ['Clay Modelling Tools', 'art_craft', 'set', 'equipment'],
  ['Glitter Powder', 'art_craft', 'packet', 'consumable'],
  ['Glitter Glue', 'art_craft', 'tube', 'consumable'],
  ['Craft Beads', 'art_craft', 'packet', 'consumable'],
  ['Pom Poms', 'art_craft', 'packet', 'consumable'],
  ['Googly Eyes', 'art_craft', 'packet', 'consumable'],
  ['Craft Feathers', 'art_craft', 'packet', 'consumable'],
  ['Pipe Cleaners', 'art_craft', 'packet', 'consumable'],
  ['Ice Cream Sticks', 'art_craft', 'packet', 'consumable'],
  ['Craft Foam Sheet', 'art_craft', 'sheet', 'consumable'],
  ['Felt Sheet', 'art_craft', 'sheet', 'consumable'],
  ['Wool Ball', 'art_craft', 'piece', 'consumable'],
  ['Craft Thread', 'art_craft', 'roll', 'consumable'],
  ['Jute Rope', 'art_craft', 'roll', 'consumable'],
  ['Satin Ribbon', 'art_craft', 'roll', 'consumable'],
  ['Decorative Stones', 'art_craft', 'packet', 'consumable'],
  ['Sequins', 'art_craft', 'packet', 'consumable'],
  ['Craft Punch', 'art_craft', 'piece', 'equipment'],
  ['Glue Gun', 'art_craft', 'piece', 'equipment'],
  ['Glue Gun Sticks', 'art_craft', 'packet', 'consumable'],
  ['Stamp Pad', 'art_craft', 'piece', 'consumable'],
  ['Stamp Pad Ink', 'art_craft', 'bottle', 'consumable'],
  ['Sketch Book', 'art_craft', 'piece', 'consumable'],
  ['Colouring Book', 'art_craft', 'piece', 'consumable'],
  ['Stencils Set', 'art_craft', 'set', 'consumable'],

  // ------------------------------------------------------------------- office
  ['Box File', 'office', 'piece', 'consumable'],
  ['Lever Arch File', 'office', 'piece', 'consumable'],
  ['Ring Binder File', 'office', 'piece', 'consumable'],
  ['Spring File', 'office', 'piece', 'consumable'],
  ['Display File', 'office', 'piece', 'consumable'],
  ['Plastic Folder', 'office', 'piece', 'consumable'],
  ['Document Sleeve', 'office', 'packet', 'consumable'],
  ['Sheet Protector', 'office', 'packet', 'consumable'],
  ['Clip Board', 'office', 'piece', 'consumable'],
  ['Expanding File', 'office', 'piece', 'consumable'],
  ['Envelope White A4', 'office', 'packet', 'consumable'],
  ['Envelope Brown A4', 'office', 'packet', 'consumable'],
  ['Cloth Lined Envelope', 'office', 'packet', 'consumable'],
  ['Window Envelope', 'office', 'packet', 'consumable'],
  ['Index Divider', 'office', 'packet', 'consumable'],
  ['Name Slip', 'office', 'packet', 'consumable'],
  ['Visiting Card Holder', 'office', 'piece', 'equipment'],
  ['Letter Tray', 'office', 'piece', 'equipment'],
  ['Magazine Holder', 'office', 'piece', 'equipment'],
  ['Document Box', 'office', 'piece', 'equipment'],
  ['Punch Single Hole', 'office', 'piece', 'equipment'],
  ['Punch Double Hole', 'office', 'piece', 'equipment'],
  ['Heavy Duty Punch', 'office', 'piece', 'equipment'],
  ['Spike File', 'office', 'piece', 'equipment'],
  ['Rubber Stamp', 'office', 'piece', 'equipment'],
  ['Self-Inking Stamp', 'office', 'piece', 'equipment'],
  ['Stamp Ink Refill', 'office', 'bottle', 'consumable'],
  ['Number Machine', 'office', 'piece', 'equipment'],
  ['Cash Box', 'office', 'piece', 'equipment'],
  ['Calculator Desktop', 'office', 'piece', 'equipment'],
  ['Whiteboard Small', 'office', 'piece', 'equipment'],
  ['Notice Board', 'office', 'piece', 'equipment'],
  ['Pin Board', 'office', 'piece', 'equipment'],
  ['Name Plate', 'office', 'piece', 'consumable'],
  ['Sign Pen', 'office', 'piece', 'consumable'],
  ['Thread Ball Office', 'office', 'piece', 'consumable'],
  ['Twine Roll', 'office', 'roll', 'consumable'],
  ['Bulldog Clip', 'office', 'box', 'consumable'],
  ['Gem Clip', 'office', 'box', 'consumable'],

  // ------------------------------------------------------------------ printing
  ['Toner Cartridge Black', 'printing', 'piece', 'consumable'],
  ['Ink Cartridge Black', 'printing', 'piece', 'consumable'],
  ['Ink Cartridge Colour', 'printing', 'piece', 'consumable'],
  ['Printer Ink Bottle Black', 'printing', 'bottle', 'consumable'],
  ['Printer Ink Bottle Cyan', 'printing', 'bottle', 'consumable'],
  ['Printer Ink Bottle Magenta', 'printing', 'bottle', 'consumable'],
  ['Printer Ink Bottle Yellow', 'printing', 'bottle', 'consumable'],
  ['Photocopy Toner', 'printing', 'piece', 'consumable'],
  ['Lamination Pouch A4', 'printing', 'packet', 'consumable'],
  ['Lamination Pouch ID', 'printing', 'packet', 'consumable'],
  ['Lamination Roll', 'printing', 'roll', 'consumable'],
  ['Spiral Binding Coil', 'printing', 'packet', 'consumable'],
  ['Binding Comb', 'printing', 'packet', 'consumable'],
  ['Binding Sheet', 'printing', 'packet', 'consumable'],
  ['Thermal Paper Roll', 'printing', 'roll', 'consumable'],
  ['Stamp Pad Refill', 'printing', 'bottle', 'consumable'],
  ['Printhead Cleaning Kit', 'printing', 'piece', 'consumable'],
  ['USB Pen Drive', 'printing', 'piece', 'equipment'],

  // ------------------------------------------------------------------ cleaning
  ['Floor Cleaner', 'cleaning', 'litre', 'consumable'],
  ['Phenyl', 'cleaning', 'litre', 'consumable'],
  ['Disinfectant Liquid', 'cleaning', 'litre', 'consumable'],
  ['Toilet Cleaner', 'cleaning', 'bottle', 'consumable'],
  ['Glass Cleaner', 'cleaning', 'bottle', 'consumable'],
  ['Dishwash Liquid', 'cleaning', 'litre', 'consumable'],
  ['Dishwash Bar', 'cleaning', 'piece', 'consumable'],
  ['Detergent Powder', 'cleaning', 'kg', 'consumable'],
  ['Detergent Bar', 'cleaning', 'piece', 'consumable'],
  ['Bleaching Powder', 'cleaning', 'kg', 'consumable'],
  ['Acid Cleaner', 'cleaning', 'bottle', 'consumable'],
  ['Scrubbing Brush', 'cleaning', 'piece', 'consumable'],
  ['Toilet Brush', 'cleaning', 'piece', 'consumable'],
  ['Scrub Pad', 'cleaning', 'piece', 'consumable'],
  ['Steel Scrubber', 'cleaning', 'piece', 'consumable'],
  ['Soft Broom', 'cleaning', 'piece', 'consumable'],
  ['Hard Broom', 'cleaning', 'piece', 'consumable'],
  ['Floor Wiper', 'cleaning', 'piece', 'equipment'],
  ['Mop with Stick', 'cleaning', 'piece', 'equipment'],
  ['Mop Refill', 'cleaning', 'piece', 'consumable'],
  ['Bucket Plastic', 'cleaning', 'piece', 'equipment'],
  ['Mug Plastic', 'cleaning', 'piece', 'consumable'],
  ['Dustpan', 'cleaning', 'piece', 'consumable'],
  ['Duster Yellow Cloth', 'cleaning', 'piece', 'consumable'],
  ['Microfibre Cloth', 'cleaning', 'piece', 'consumable'],
  ['Garbage Bag Small', 'cleaning', 'packet', 'consumable'],
  ['Garbage Bag Large', 'cleaning', 'packet', 'consumable'],
  ['Dustbin Small', 'cleaning', 'piece', 'equipment'],
  ['Dustbin Large', 'cleaning', 'piece', 'equipment'],
  ['Rubber Gloves', 'cleaning', 'pair', 'consumable'],
  ['Cobweb Brush', 'cleaning', 'piece', 'equipment'],
  ['Drain Cleaner', 'cleaning', 'bottle', 'consumable'],
  ['Naphthalene Balls', 'cleaning', 'packet', 'consumable'],
  ['Room Freshener Spray', 'cleaning', 'bottle', 'consumable'],

  // ---------------------------------------------------------------- sanitation
  ['Hand Wash Liquid', 'sanitation', 'litre', 'consumable'],
  ['Hand Sanitizer', 'sanitation', 'bottle', 'consumable'],
  ['Toilet Soap', 'sanitation', 'piece', 'consumable'],
  ['Liquid Soap Refill', 'sanitation', 'litre', 'consumable'],
  ['Toilet Roll', 'sanitation', 'roll', 'consumable'],
  ['Tissue Paper Box', 'sanitation', 'box', 'consumable'],
  ['Napkin Roll', 'sanitation', 'roll', 'consumable'],
  ['Paper Napkin', 'sanitation', 'packet', 'consumable'],
  ['Sanitary Napkin', 'sanitation', 'packet', 'consumable'],
  ['Sanitary Disposal Bag', 'sanitation', 'packet', 'consumable'],
  ['Air Freshener Block', 'sanitation', 'piece', 'consumable'],
  ['Urinal Cube', 'sanitation', 'packet', 'consumable'],
  ['Toilet Paper Dispenser', 'sanitation', 'piece', 'equipment'],
  ['Soap Dispenser', 'sanitation', 'piece', 'equipment'],
  ['Sanitizer Dispenser', 'sanitation', 'piece', 'equipment'],
  ['Hand Towel', 'sanitation', 'piece', 'consumable'],
  ['Face Mask', 'sanitation', 'box', 'consumable'],
  ['Disposable Gloves', 'sanitation', 'box', 'consumable'],
  ['Mosquito Repellent', 'sanitation', 'bottle', 'consumable'],
  ['Insect Killer Spray', 'sanitation', 'bottle', 'consumable'],

  // ---------------------------------------------------------------- electrical
  ['LED Bulb 9W', 'electrical', 'piece', 'consumable'],
  ['LED Bulb 12W', 'electrical', 'piece', 'consumable'],
  ['LED Tube Light', 'electrical', 'piece', 'consumable'],
  ['Tube Light Choke', 'electrical', 'piece', 'consumable'],
  ['Tube Light Starter', 'electrical', 'piece', 'consumable'],
  ['CFL Bulb', 'electrical', 'piece', 'consumable'],
  ['Fan Capacitor', 'electrical', 'piece', 'consumable'],
  ['Fan Regulator', 'electrical', 'piece', 'consumable'],
  ['Switch', 'electrical', 'piece', 'consumable'],
  ['Socket', 'electrical', 'piece', 'consumable'],
  ['Plug Top', 'electrical', 'piece', 'consumable'],
  ['Extension Board', 'electrical', 'piece', 'equipment'],
  ['Multi Plug', 'electrical', 'piece', 'consumable'],
  ['Insulation Tape', 'electrical', 'roll', 'consumable'],
  ['Electrical Wire', 'electrical', 'metre', 'consumable'],
  ['MCB', 'electrical', 'piece', 'consumable'],
  ['Fuse Wire', 'electrical', 'packet', 'consumable'],
  ['AA Battery', 'electrical', 'packet', 'consumable'],
  ['AAA Battery', 'electrical', 'packet', 'consumable'],
  ['9V Battery', 'electrical', 'piece', 'consumable'],
  ['Button Cell Battery', 'electrical', 'piece', 'consumable'],
  ['Rechargeable Battery', 'electrical', 'piece', 'consumable'],
  ['Holder Bulb', 'electrical', 'piece', 'consumable'],
  ['Buzzer', 'electrical', 'piece', 'consumable'],
  ['Indicator Lamp', 'electrical', 'piece', 'consumable'],
  ['Extension Cord', 'electrical', 'piece', 'equipment'],

  // ------------------------------------------------------------------ hardware
  ['Iron Nails', 'hardware', 'packet', 'consumable'],
  ['Wood Screws', 'hardware', 'packet', 'consumable'],
  ['Self-Tapping Screws', 'hardware', 'packet', 'consumable'],
  ['Nut Bolt Set', 'hardware', 'packet', 'consumable'],
  ['Wall Plug', 'hardware', 'packet', 'consumable'],
  ['Hinges', 'hardware', 'piece', 'consumable'],
  ['Door Handle', 'hardware', 'piece', 'consumable'],
  ['Tower Bolt', 'hardware', 'piece', 'consumable'],
  ['Door Lock', 'hardware', 'piece', 'consumable'],
  ['Padlock', 'hardware', 'piece', 'consumable'],
  ['Hammer', 'hardware', 'piece', 'equipment'],
  ['Screwdriver Set', 'hardware', 'set', 'equipment'],
  ['Plier', 'hardware', 'piece', 'equipment'],
  ['Wrench', 'hardware', 'piece', 'equipment'],
  ['Measuring Tape', 'hardware', 'piece', 'equipment'],
  ['Spirit Level', 'hardware', 'piece', 'equipment'],
  ['Hand Drill', 'hardware', 'piece', 'equipment'],
  ['Drill Bit Set', 'hardware', 'set', 'consumable'],
  ['Hacksaw', 'hardware', 'piece', 'equipment'],
  ['Hacksaw Blade', 'hardware', 'piece', 'consumable'],
  ['Sandpaper', 'hardware', 'sheet', 'consumable'],
  ['Enamel Paint', 'hardware', 'litre', 'consumable'],
  ['Distemper Paint', 'hardware', 'kg', 'consumable'],
  ['Primer Paint', 'hardware', 'litre', 'consumable'],
  ['Paint Brush 2 inch', 'hardware', 'piece', 'consumable'],
  ['Paint Roller', 'hardware', 'piece', 'consumable'],
  ['Putty', 'hardware', 'kg', 'consumable'],
  ['White Cement', 'hardware', 'kg', 'consumable'],
  ['M-Seal', 'hardware', 'piece', 'consumable'],
  ['Araldite', 'hardware', 'piece', 'consumable'],
  ['Fevicol', 'hardware', 'kg', 'consumable'],
  ['Teflon Tape', 'hardware', 'roll', 'consumable'],
  ['PVC Pipe', 'hardware', 'piece', 'consumable'],
  ['Pipe Fitting', 'hardware', 'piece', 'consumable'],
  ['Tap', 'hardware', 'piece', 'consumable'],
  ['Washer', 'hardware', 'packet', 'consumable'],
  ['Cable Tie', 'hardware', 'packet', 'consumable'],
  ['Nylon Rope', 'hardware', 'metre', 'consumable'],
  ['Wheel Caster', 'hardware', 'piece', 'consumable'],

  // -------------------------------------------------------------------- events
  ['Balloons', 'events', 'packet', 'consumable'],
  ['Helium Balloons', 'events', 'packet', 'consumable'],
  ['Paper Buntings', 'events', 'piece', 'consumable'],
  ['Plastic Flag Bunting', 'events', 'piece', 'consumable'],
  ['Ribbon Roll', 'events', 'roll', 'consumable'],
  ['Decoration Net', 'events', 'metre', 'consumable'],
  ['Crepe Streamer', 'events', 'roll', 'consumable'],
  ['Banner Cloth', 'events', 'metre', 'consumable'],
  ['Flex Banner', 'events', 'piece', 'consumable'],
  ['Welcome Banner', 'events', 'piece', 'consumable'],
  ['Stage Backdrop Cloth', 'events', 'metre', 'consumable'],
  ['Artificial Flowers', 'events', 'piece', 'consumable'],
  ['Flower Garland', 'events', 'piece', 'consumable'],
  ['Decorative Light String', 'events', 'piece', 'equipment'],
  ['Serial Light', 'events', 'piece', 'equipment'],
  ['Candle', 'events', 'packet', 'consumable'],
  ['Diya', 'events', 'packet', 'consumable'],
  ['Camphor', 'events', 'packet', 'consumable'],
  ['Incense Sticks', 'events', 'packet', 'consumable'],
  ['Confetti', 'events', 'packet', 'consumable'],
  ['Party Popper', 'events', 'piece', 'consumable'],
  ['Medal', 'events', 'piece', 'consumable'],
  ['Trophy', 'events', 'piece', 'consumable'],
  ['Certificate Paper', 'events', 'packet', 'consumable'],
  ['Sash', 'events', 'piece', 'consumable'],
  ['Badge Ribbon', 'events', 'piece', 'consumable'],
  ['Table Cloth', 'events', 'piece', 'consumable'],
  ['Bouquet', 'events', 'piece', 'consumable'],

  // ------------------------------------------------------------------ identity
  ['ID Card Blank', 'identity', 'packet', 'consumable'],
  ['ID Card Holder', 'identity', 'piece', 'consumable'],
  ['Lanyard', 'identity', 'piece', 'consumable'],
  ['Visitor Badge', 'identity', 'piece', 'consumable'],
  ['Name Badge', 'identity', 'piece', 'consumable'],
  ['Safety Pin Badge', 'identity', 'piece', 'consumable'],
  ['Barcode Label Roll', 'identity', 'roll', 'consumable'],
  ['Asset Sticker', 'identity', 'sheet', 'consumable'],
  ['QR Code Sticker', 'identity', 'sheet', 'consumable'],
  ['Round Sticker Dot', 'identity', 'packet', 'consumable'],
  ['Price Label', 'identity', 'roll', 'consumable'],
  ['Signage Board', 'identity', 'piece', 'consumable'],
  ['Door Name Plate', 'identity', 'piece', 'consumable'],

  // ------------------------------------------------------------------- kitchen
  ['Paper Cup', 'kitchen', 'packet', 'consumable'],
  ['Paper Plate', 'kitchen', 'packet', 'consumable'],
  ['Plastic Spoon', 'kitchen', 'packet', 'consumable'],
  ['Plastic Glass', 'kitchen', 'packet', 'consumable'],
  ['Tissue Roll Kitchen', 'kitchen', 'roll', 'consumable'],
  ['Aluminium Foil', 'kitchen', 'roll', 'consumable'],
  ['Cling Film', 'kitchen', 'roll', 'consumable'],
  ['Butter Paper Roll', 'kitchen', 'roll', 'consumable'],
  ['Garbage Bag Kitchen', 'kitchen', 'packet', 'consumable'],
  ['Tea Powder', 'kitchen', 'kg', 'consumable'],
  ['Coffee Powder', 'kitchen', 'kg', 'consumable'],
  ['Sugar', 'kitchen', 'kg', 'consumable'],
  ['Milk Powder', 'kitchen', 'kg', 'consumable'],
  ['Drinking Water Can', 'kitchen', 'can', 'consumable'],
  ['Gas Cylinder', 'kitchen', 'piece', 'consumable'],
  ['Match Box', 'kitchen', 'box', 'consumable'],
  ['Gas Lighter', 'kitchen', 'piece', 'equipment'],
  ['Steel Plate', 'kitchen', 'piece', 'equipment'],
  ['Steel Glass', 'kitchen', 'piece', 'equipment'],
  ['Serving Spoon', 'kitchen', 'piece', 'equipment'],
  ['Water Jug', 'kitchen', 'piece', 'equipment'],
  ['Casserole', 'kitchen', 'piece', 'equipment'],
  ['Apron', 'kitchen', 'piece', 'consumable'],
  ['Hair Net', 'kitchen', 'packet', 'consumable'],

  // -------------------------------------------------------------------- garden
  ['Flower Seeds', 'garden', 'packet', 'consumable'],
  ['Vegetable Seeds', 'garden', 'packet', 'consumable'],
  ['Garden Soil', 'garden', 'kg', 'consumable'],
  ['Manure', 'garden', 'kg', 'consumable'],
  ['Fertilizer', 'garden', 'kg', 'consumable'],
  ['Cocopeat', 'garden', 'kg', 'consumable'],
  ['Pesticide Spray', 'garden', 'bottle', 'consumable'],
  ['Plastic Pot', 'garden', 'piece', 'consumable'],
  ['Clay Pot', 'garden', 'piece', 'consumable'],
  ['Grow Bag', 'garden', 'piece', 'consumable'],
  ['Watering Can', 'garden', 'piece', 'equipment'],
  ['Garden Hose', 'garden', 'metre', 'equipment'],
  ['Sprayer', 'garden', 'piece', 'equipment'],
  ['Spade', 'garden', 'piece', 'equipment'],
  ['Khurpi', 'garden', 'piece', 'equipment'],
  ['Pruning Shears', 'garden', 'piece', 'equipment'],
  ['Rake', 'garden', 'piece', 'equipment'],
  ['Lawn Mower Blade', 'garden', 'piece', 'consumable'],
  ['Garden Gloves', 'garden', 'pair', 'consumable'],
  ['Plant Support Stick', 'garden', 'piece', 'consumable'],

  // ----------------------------------------------------------------- first_aid
  ['Cotton Roll', 'first_aid', 'roll', 'consumable'],
  ['Bandage Roll', 'first_aid', 'piece', 'consumable'],
  ['Crepe Bandage', 'first_aid', 'piece', 'consumable'],
  ['Adhesive Bandage', 'first_aid', 'box', 'consumable'],
  ['Gauze Pad', 'first_aid', 'packet', 'consumable'],
  ['Antiseptic Liquid', 'first_aid', 'bottle', 'consumable'],
  ['Antiseptic Cream', 'first_aid', 'tube', 'consumable'],
  ['Pain Relief Spray', 'first_aid', 'bottle', 'consumable'],
  ['Pain Balm', 'first_aid', 'piece', 'consumable'],
  ['Surgical Tape', 'first_aid', 'roll', 'consumable'],
  ['Thermometer Digital', 'first_aid', 'piece', 'equipment'],
  ['Disposable Gloves First Aid', 'first_aid', 'box', 'consumable'],
  ['Burn Ointment', 'first_aid', 'tube', 'consumable'],
  ['ORS Sachet', 'first_aid', 'packet', 'consumable'],
  ['Glucose Powder', 'first_aid', 'packet', 'consumable'],
  ['Ice Pack', 'first_aid', 'piece', 'consumable'],
  ['Scissors First Aid', 'first_aid', 'piece', 'equipment'],
  ['Tweezers', 'first_aid', 'piece', 'equipment'],
  ['Dettol Soap', 'first_aid', 'piece', 'consumable'],
  ['First Aid Box', 'first_aid', 'piece', 'equipment'],

  // ----------------------------------------------------------------- classroom
  ['Globe', 'classroom', 'piece', 'equipment'],
  ['World Map', 'classroom', 'piece', 'consumable'],
  ['India Map', 'classroom', 'piece', 'consumable'],
  ['Alphabet Chart', 'classroom', 'piece', 'consumable'],
  ['Number Chart', 'classroom', 'piece', 'consumable'],
  ['Science Chart', 'classroom', 'piece', 'consumable'],
  ['Wall Chart Set', 'classroom', 'set', 'consumable'],
  ['Flash Cards', 'classroom', 'set', 'consumable'],
  ['Abacus', 'classroom', 'piece', 'equipment'],
  ['Geometry Board Set', 'classroom', 'set', 'equipment'],
  ['Wooden Blocks', 'classroom', 'set', 'consumable'],
  ['Magnetic Letters', 'classroom', 'set', 'consumable'],
  ['Counting Beads', 'classroom', 'set', 'consumable'],
  ['Skeleton Model', 'classroom', 'piece', 'equipment'],
  ['Human Body Chart', 'classroom', 'piece', 'consumable'],
  ['Solar System Model', 'classroom', 'piece', 'equipment'],
  ['Class Pointer Stick', 'classroom', 'piece', 'consumable'],
  ['Magnetic Whiteboard', 'classroom', 'piece', 'equipment'],
  ['Display Chart Stand', 'classroom', 'piece', 'equipment'],
  ['Educational Puzzle', 'classroom', 'set', 'consumable'],
];

export const SUPPLY_ITEM_SEEDS: SupplyItemSeed[] = ROWS.map(
  ([name, categoryCode, unit, itemType]) => ({ name, categoryCode, unit, itemType })
);
