provider:
  name: aws
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    ${file(../../configs/${self:provider.stage}/${self:provider.stage}.yml)}
  $<<: ${file(../global-config-${self:provider.stage}.yml):provider}

custom:
  prefix: itsmyskool
  baseServiceName: academic-calendar-service
  fullServiceName: ${self:custom.prefix}-${self:custom.baseServiceName}
  customDomain:
   basePath: 'academic-calendar'
  $<<: ${file(../global-config-${self:provider.stage}.yml):custom}

service: ${self:provider.stage}-${self:custom.fullServiceName}
configValidationMode: off

plugins:
  - ../../plugins/serverless-merge-config.js
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
  - ../../plugins/serverless-cors-defaults.js
  - ../../plugins/serverless-authorizer.js

functions: ${file(academic-calendar-endpoints.yml)}

$<<: ${file(../global-config-${self:provider.stage}.yml):resources}
